### ISSUE TITLE
Why you don't recommend the "while" approach?

### ISSUE THREAD

**Issue by RobertoSchneiders** [SocialbitGmbH/AWSBeanstalkSwap#1]
`The same but WHILE deploying (not recommended!)`

I need the swap already configured at some point in the first deploy, because the `assets pre:compile` is crashing with `Cannot allocate memory - node` error. 

Thanks for sharing the config.

**Comment by blaues0cke** [comment]
In our case the deployment took quite too long since amazon waits until all tasks are finished. So you can still do this while deploying, but you have to wait longer for the green :heavy_check_mark: :-)

**Comment by RobertoSchneiders** [comment]
Nice. 

I need to do this while deploying because we have facing out of memory errors on assets compilation (which is part of the deploy process). 

thanks
